// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantOrderingSystem.Data;

#nullable disable

namespace RestaurantOrderingSystem.Migrations
{
    [DbContext(typeof(RestaurantDbContext))]
    partial class RestaurantDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestaurantOrderingSystem.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Small plates to begin the meal.",
                            Name = "Starters"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Signature plates and hearty bowls.",
                            Name = "Mains"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Sweet finishes made in-house.",
                            Name = "Desserts"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Fresh coolers, coffee, and tea.",
                            Name = "Drinks"
                        });
                });

            modelBuilder.Entity("RestaurantOrderingSystem.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Golden paneer cubes with mint yogurt dip.",
                            ImageUrl = "/images/menu/paneer-bites.jpg",
                            IsAvailable = true,
                            IsFeatured = true,
                            Name = "Crispy Paneer Bites",
                            Price = 229m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Skin-on fries tossed with garlic butter and parsley.",
                            ImageUrl = "/images/menu/fries.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Name = "Garlic Herb Fries",
                            Price = 149m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Smoky chicken, saffron rice, salad, and house chutney.",
                            ImageUrl = "/images/menu/chicken-bowl.jpg",
                            IsAvailable = true,
                            IsFeatured = true,
                            Name = "Tandoori Chicken Bowl",
                            Price = 389m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Thin crust pizza with peppers, olives, corn, and mozzarella.",
                            ImageUrl = "/images/menu/pizza.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Name = "Veggie Supreme Pizza",
                            Price = 449m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Penne in parmesan cream sauce with sauteed mushrooms.",
                            ImageUrl = "/images/menu/pasta.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Name = "Creamy Mushroom Pasta",
                            Price = 349m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Description = "Warm chocolate cake with vanilla ice cream.",
                            ImageUrl = "/images/menu/lava-cake.jpg",
                            IsAvailable = true,
                            IsFeatured = true,
                            Name = "Chocolate Lava Cake",
                            Price = 199m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            Description = "Fresh lime, mint, soda, and crushed ice.",
                            ImageUrl = "/images/menu/cooler.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Name = "Mint Lime Cooler",
                            Price = 119m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Description = "Chilled coffee blended with milk and a light cream top.",
                            ImageUrl = "/images/menu/cold-coffee.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Name = "Cold Coffee",
                            Price = 159m
                        });
                });

            modelBuilder.Entity("RestaurantOrderingSystem.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("DeliveryFee")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("OrderedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Tax")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("RestaurantOrderingSystem.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("RestaurantOrderingSystem.Models.MenuItem", b =>
                {
                    b.HasOne("RestaurantOrderingSystem.Models.Category", "Category")
                        .WithMany("MenuItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("RestaurantOrderingSystem.Models.OrderItem", b =>
                {
                    b.HasOne("RestaurantOrderingSystem.Models.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantOrderingSystem.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("RestaurantOrderingSystem.Models.Category", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("RestaurantOrderingSystem.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
